AWSTemplateFormatVersion: 2010-09-09
Parameters:
  AvailabilityZone:
    Type: AWS::EC2::AvailabilityZone::Name
  InstanceTypePar:
    Type: String
    Default: t2.micro
    Description: Enter instance size. Default is t2.micro.
  AMI:
    Type: String
    Default: ami-0a49b025fffbbdac6
    Description: Ubuntu server
  KeyPairName: 
    Type: String
    Default: Key-for-Frankfurt
    Description: The name of an existing Amazon EC2 key pair in this region to use to SSH into the Amazon EC2 instances.

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      ImageId: !Ref AMI
      InstanceType: !Ref InstanceTypePar
      KeyName: !Ref KeyPairName
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash -xe
          sudo apt-get update -y
          sudo apt-get install nginx -y
          sudo cat << EOF > /var/www/html/index.nginx-debian.html
          <!DOCTYPE html>
            <html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
              <title>Info</title>
          </head>
          <body>
            <div>
              <h3>Hello world from Crash course DevOps</h3>
              <h3>Author - Oleh Ionis</h3>
            </div>
          </body></html>
          EOF

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join ["-", [webapp-security-group, dev]]
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0